### PR TITLE
Prevent a division by zero error

### PR DESCRIPTION
**Pull request by alexfraundorf-com**
Some of my fit files were causing this line to throw a division by zero error.  I added a check to prevent this from happening.

### CODE REVIEW

**Comment by adriangibbons** [comment]
Hi, I see the issue - perhaps it would be a bit clearer in the code if the below is inserted at Ln 1969?
```php
if ($this->data_mesgs[$message][$field] === 0) {  // Prevent divide by zero error
    continue;  // Skip to next foreach() iteration
}
```

**Comment by alexfraundorf-com** [comment]
Adrian, I have updated the fix based on your suggestion.
Also, thank you for writing and sharing this library!

**Comment by adriangibbons** [comment]
Hi @alexfraundorf-com - thank you very much for your contribution!

There seems to be trailing whitespace(s) after some of the new lines of code - would you mind tidying it up and then I'll happily merge. I don't seem to be able to do this myself.

Adrian.

**Comment by alexfraundorf-com** [comment]
Trailing spaces are removed.  Thanks!

**Comment by adriangibbons** [comment]
Thank you very much for your contribution! 👍

**Comment by alexfraundorf-com** [comment]
Thanks!
Is there any way for this fix to be put into a tag?  I would like to be able to pull in the most recent version using composer, but not by requiring master.
Have a great day!

**Comment by adriangibbons** [comment]
I'll create a minor release now!

**Comment by alexfraundorf-com** [comment]
Thank you!  I see 3.2.2 on Github, but not on Packagist (where composer pulls versions from).  I'm guessing this means that there is not a automated webhook set up, so I believe you will need to login to packagist and update the package.

**Comment by adriangibbons** [comment]
Hi - I've logged in to packagist and maybe that triggered something but I see v3.2.2 there. Let me know if still an issue!

**Comment by adriangibbons** [comment]
Got an email from Github - would seem that my packagist login probably did fix things as I got:

> Previously, a third-party OAuth application (Packagist) did not have any scopes. It was recently granted additional scopes (admin:repo_hook and read:org)...

**Comment by alexfraundorf-com** [comment]
That did the trick.  Composer is now pulling in 3.2.2.  Thank you for taking care of that and for sharing your library.  Have a great day!

**Pull request merged**
